services:
  ospos-app:
    image: jekkos/opensourcepos:master
    restart: unless-stopped
    depends_on:
      - ospos-db
    networks:
      - ospos-network
    volumes:
      - ospos-uploads:/app/writable/uploads
      - ospos-logs:/app/writable/logs
    environment:
      - CI_ENVIRONMENT=${CI_ENVIRONMENT:-production}
      - FORCE_HTTPS=${FORCE_HTTPS:-false}
      - PHP_TIMEZONE=${PHP_TIMEZONE:-UTC}
      - MYSQL_USERNAME=${MYSQL_USERNAME:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pointofsale}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME:-ospos}
      - MYSQL_HOST_NAME=ospos-db

  ospos-db:
    image: mysql:8.0
    restart: unless-stopped
    networks:
      - ospos-network
    volumes:
      - ospos-db-data:/var/lib/mysql
      - ospos-db-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DB_NAME:-ospos}
      - MYSQL_USER=${MYSQL_USERNAME:-admin}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-pointofsale}
    command: --default-authentication-plugin=mysql_native_password

  # SQL initialization container
  ospos-sql-init:
    image: jekkos/opensourcepos:sql-master
    command: /bin/sh -c 'exit 0'
    volumes:
      - ospos-db-init:/docker-entrypoint-initdb.d
    depends_on:
      - ospos-db

volumes:
  ospos-db-data:
  ospos-db-init:
  ospos-uploads:
  ospos-logs:

networks:
  ospos-network:
    driver: bridge